name: JSON Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: List changed files
        run: |
          echo "List of changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      - name: Validate JSON files
        run: |
          # Retrieve the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

          # Loop through the changed files
          for file in $changed_files; do
            # Check if the file is a JSON file
            if [[ $file == *.json ]]; then
              echo "Validating JSON file: $file"
              python scripts/validate_json.py "${{ github.workspace }}/$file"
            fi
          done
        shell: bash
